language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true

notifications:
  email:
    recipients:
    - mete@katircioglu.net
    on_success: change
    on_failure: always

branches:
  only:
  - master
